import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    card: {
        margin: 8,
        width: 200,
        height: "93%",
        padding: 16,
        borderRadius: 12,
        backgroundColor: '#fff',
        elevation: 8,
        shadowRadius: 6,
        shadowColor: '#000',
        shadowOpacity: 0.25,
        shadowOffset: { width: 0, height: 4 },
    },
    cardActive: {
        margin: 8,
        width: 200,
        height: "93%",
        padding: 16,
        borderRadius: 12,
        backgroundColor: '#e0f7fa',
        elevation: 8,
        shadowRadius: 6,
        shadowColor: '#000',
        shadowOpacity: 0.25,
        shadowOffset: { width: 0, height: 4 },
    },
    section_header: {
        marginBottom: 12,
        flexDirection: 'row',
        alignItems: 'flex-start',
        justifyContent: 'space-between',
    },
    deviceName: {
        height: 44,
        fontSize: 18,
        maxWidth: '80%',
        fontWeight: 'bold',
    },
    connectedStatus: {
        width: 10,
        height: 10,
        borderRadius: 5,
        backgroundColor: 'green',
    },
    disconnectedStatus: {
        width: 10,
        height: 10,
        borderRadius: 5,
        backgroundColor: 'red',
    },
    section_body: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
    },
    section_footer: {
        padding: 4,
        marginTop: 8,
        borderRadius: 12,
        alignSelf: 'center',
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#f0f0f0',
    },
    tipIcon: {
        width: 16,
        height: 16,
        marginRight: 6,
        tintColor: '#666',
    },
    tips: {
        fontSize: 14,
        color: '#666',
        textAlign: 'center',
    },
    digitalSensor: {
        marginTop: 12,
        alignItems: 'center',
    },
    digitalSensorHigh: {
        height: 100,
        width: 100,
        borderRadius: 50,
        borderWidth: 2,
        borderColor: 'red',
        backgroundColor: '#ffcccc',
    },
    digitalSensorLow: {
        width: 100,
        height: 100,
        borderWidth: 2,
        borderRadius: 50,
        borderColor: 'green',
        backgroundColor: '#ccffcc',
    },
    digitalSensorText: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#333',
        marginTop: 16,
    },
    overlay: {
        ...StyleSheet.absoluteFillObject,
        backgroundColor: "rgba(255, 255, 255, 0.6)",
        justifyContent: "center",
        alignItems: "center",
        borderRadius: 12,
        overflow: "hidden",
    },
});
