import { StyleSheet } from 'react-native';

export const searchWidgetStyle = StyleSheet.create({
    container: {
        height: 50,
        width: '100%',
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'transparent',
    },
    dropdownContainer: {
        width: '25%',
        height: '100%',
        margin: 0,
        padding: 0,
        backgroundColor: 'transparent',
    },
    dropdown: {
        height: '100%',
        marginTop: 0,
        borderWidth: 0,
        borderRadius: 0,
        borderLeftWidth: 1,
        borderTopLeftRadius: 12,
        borderBottomLeftRadius: 12,
        backgroundColor: '#fff'
    },
    inputWithDropdown: {
        flex: 1,
        height: '100%',
        borderColor: '#ccc',
        borderWidth: 0,
        borderLeftWidth: 1,
        paddingHorizontal: 6,
        borderTopRightRadius: 12,
        borderBottomRightRadius: 12,
        color: '#000',
        backgroundColor: '#fff',
    },
    input: {
        flex: 1,
        height: '100%',
        borderColor: '#ccc',
        borderWidth: 0,
        borderLeftWidth: 1,
        paddingHorizontal: 12,
        borderRadius: 12,
        color: '#000',
        backgroundColor: '#fff',
    },
    button: {
        height: '100%',
        marginLeft: 8,
        borderRadius: 12,
        paddingHorizontal: 16,
        paddingLeft: 20,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#007BFF',
    },
        timeRangeButton: {
        justifyContent: 'center',
        paddingHorizontal: 12,
    },
    timeRangeText: {
        fontSize: 14,
        color: '#3b3b3b67',
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(51, 51, 51, 0.4)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    modalContent: {
        backgroundColor: 'white',
        padding: 20,
        borderRadius: 10,
        width: '80%',
    },
    modalTitle: {
        fontSize: 16,
        fontWeight: 'bold',
        marginBottom: 15,
        textAlign: 'center',
    },
    modalButton: {
        marginTop: 15,
        padding: 10,
        backgroundColor: '#A855F7',
        borderRadius: 16,
        alignItems: 'center',
    },
    modalButtonText: {
        color: 'white',
        fontWeight: 'bold',
    },
});
