import { StyleSheet } from 'react-native';

export const navigationBarStyle = StyleSheet.create({
    container: {
        flex: 1,
        alignItems: 'center',
        flexDirection: 'row',
        justifyContent: 'space-between',
        bottom: 20,
        height: 68,
        width: '100%',
        alignSelf: 'center',
        position: 'absolute',
        paddingHorizontal: 16,
        backgroundColor: 'transparent',
    },
    tabBar: {
        flex: 1,
        height: 65,
        borderRadius: 36,
        paddingVertical: 4,
        flexDirection: 'row',
        backgroundColor: '#ffffff',
        justifyContent: 'space-around',
        alignItems: 'center',
        overflow: 'hidden',
    },
    inactiveTab: {
        width: 65,
        height: '100%',
        borderRadius: 36,
        alignItems: 'center',
        marginHorizontal: 4,
        justifyContent: 'center',
        backgroundColor: '#BABABA'
    },
    activeTab: {
        flex: 1,
        borderRadius: 36,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#050041'
    },
    voiceButton: {
        position: 'absolute',
        bottom: 82,
        right: 16,
        alignSelf: 'center',
        width: 60,
        height: 60,
        borderRadius: 16,
        backgroundColor: '#FFFFFF',
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
        elevation: 5,
    },
    voiceIcon: {
        width: 24,
        height: 24,
    },
});