version: "3.8"

services:
  auth-service:
    build:
      context: ../auth-service
      dockerfile: Dockerfile
    env_file:
      - ../auth-service/.env
    ports:
      - "8081:8081"
    depends_on:
      - auth-db
    restart: unless-stopped

  auth-db:
    image: postgres:15
    env_file:
      - ../auth-service/.env
    ports:
      - "5433:5432"
    volumes:
      - auth_db_data:/var/lib/postgresql/data 
    restart: unless-stopped

  core-service:
    build:
      context: ../core-service
      dockerfile: Dockerfile
    env_file:
      - ../core-service/.env
    ports:
      - "8082:8082"
    depends_on:
      - auth-service
      - core-db
      - mqtt-broker
    restart: unless-stopped

  core-db:
    image: postgres:15
    env_file:
      - ../core-service/.env
    ports:
      - "5434:5432"
    volumes:
      - core_db_data:/var/lib/postgresql/data
    restart: unless-stopped

  mqtt-broker:
    image: eclipse-mosquitto:2.0
    env_file:
      - ../core-service/.env
    ports:
      - "1883:1883"
    volumes:
      - ../core-service/mosquitto/config:/mosquitto/config
      - ../core-service/mosquitto/mqtt_init.sh:/mqtt_init.sh
    entrypoint: ["/mqtt_init.sh"]
    restart: unless-stopped

volumes:
  auth_db_data:
  core_db_data:
