version: "3.8"

services:
  auth-service:
    build:
      context: ../auth-service
      dockerfile: Dockerfile
    container_name: auth_service
    environment:
      AUTH_DB_PORT: ${AUTH_DB_PORT}
      AUTH_DB_HOST: ${AUTH_DB_HOST}
      AUTH_DB_USER: ${AUTH_DB_USER}
      AUTH_DB_PASS: ${AUTH_DB_PASS}
      AUTH_DB_NAME: ${AUTH_DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "8081:8081"
    depends_on:
      - auth-db
    restart: unless-stopped

  auth-db:
    image: postgres:15
    container_name: auth_db
    environment:
      - POSTGRES_USER=${AUTH_DB_USER}
      - POSTGRES_PASSWORD=${AUTH_DB_PASS}
      - POSTGRES_DB=${AUTH_DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - auth_db_data:/var/lib/postgresql/data 
    restart: unless-stopped

  core-service:
    build:
      context: ../core-service
      dockerfile: Dockerfile
    container_name: core_service
    env_file:
      - ../core-service/.env
    ports:
      - "8082:8082"
    depends_on:
      - auth-service
      - core-db
      - mqtt-broker
    restart: unless-stopped

  core-db:
    image: postgres:15
    container_name: core_db
    environment:
      - POSTGRES_USER=${CORE_DB_USER}
      - POSTGRES_PASSWORD=${CORE_DB_PASS}
      - POSTGRES_DB=${CORE_DB_NAME}
    ports:
      - "5434:5432"
    volumes:
      - core_db_data:/var/lib/postgresql/data
    restart: unless-stopped

  mqtt-broker:
    image: eclipse-mosquitto:2.0
    container_name: mqtt_broker
    environment:
      - MOSQUITTO_USER=${MQTT_BROKER_USER}
      - MOSQUITTO_PASS=${MQTT_BROKER_PASS}
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/mqtt_init.sh:/mqtt_init.sh
    entrypoint: ["/mqtt_init.sh"]
    restart: unless-stopped

volumes:
  auth_db_data:
  core_db_data:
