version: "3.8"

services:
  auth-service:
    build:
      context: ../auth-service
      dockerfile: Dockerfile
    env_file:
      - ../auth-service/.env
    ports:
      - "8081:8081"
    depends_on:
      - auth-db
    restart: unless-stopped

  auth-db:
    image: postgres:15
    env_file:
      - ../auth-service/.env
    ports:
      - "5433:5432"
    volumes:
      - auth_db_data:/var/lib/postgresql/data 
    restart: unless-stopped

volumes:
  auth_db_data:
