services:
  auth-service:
    build:
      context: ../auth-service
      dockerfile: Dockerfile
    container_name: auth_service
    env_file:
      - .env
    ports:
      - "8081:8081"
    depends_on:
      - auth-db
    restart: unless-stopped

  auth-db:
    image: postgres:15
    container_name: auth_db
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - auth_db_data:/var/lib/postgresql/data
    restart: unless-stopped

  core-service:
    build:
      context: ../core-service
      dockerfile: Dockerfile
    container_name: core_service
    env_file:
      - .env
    ports:
      - "8082:8082"
    depends_on:
      - core-db
      - mqtt-broker
    restart: unless-stopped

  core-db:
    image: postgres:15
    container_name: core_db
    env_file:
      - .env
    ports:
      - "5434:5432"
    volumes:
      - core_db_data:/var/lib/postgresql/data
    restart: unless-stopped

  gateway:
    build:
      context: ../gateway
      dockerfile: Dockerfile
    container_name: gateway
    ports:
      - "8080:8080"
    depends_on:
      - auth-service
      - core-service
    restart: unless-stopped

  mqtt-broker:
    image: eclipse-mosquitto:2.0
    container_name: mqtt_broker
    env_file:
      - .env
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/mqtt_init.sh:/mqtt_init.sh
    entrypoint: ["/mqtt_init.sh"]
    restart: unless-stopped

volumes:
  auth_db_data:
  core_db_data:
