database:
  host: ${AUTH_DB_HOST}
  port: ${AUTH_DB_PORT}
  database: ${AUTH_DB_NAME}
  password: ${AUTH_DB_PASS}
  username: ${AUTH_DB_USER}

server:
  host: localhost
  port: 8081
  base_path: auth-service/api/v1/auth
  jwt_secret: ${JWT_SECRET}